management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
spring:
  webflux:
    base-path: /infra/nam/oauth/clients/validator