apiVersion: apps/v1
kind: Deployment
metadata:
  name: flais-nam-oauth-client-validator
spec:
  selector:
    matchLabels:
      app: flais-nam-oauth-client-validator
  replicas: 1
  template:
    metadata:
      labels:
        app: flais-nam-oauth-client-validator
      annotations:
        prometheus.io/path: /infra/nam/oauth/clients/validator/actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: flais-nam-oauth-client-validator
          image: "ghcr.io/fintlabs/flais-nam-oauth-client-validator:sha-0000000"
          env:
            - name: logging.level.no.fintlabs
              value: DEBUG
            - name: spring.webflux.base-path
              value: /infra/nam/oauth/clients/validator
            - name: spring.ldap.url
              value: ldap://localhost:389
          envFrom:
            - secretRef:
                name: flais-nam-oauth-client-validator
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /infra/nam/oauth/clients/validator/actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /infra/nam/oauth/clients/validator/actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            limits:
              memory: 350Mi
              cpu: 200m
            requests:
              memory: 300Mi
              cpu: 50m

        - name: stunnel
          image: ghcr.io/fintlabs/vigo-auth-organisation-selector-ldap-proxy:sha-05c9d22
          env:
            - name: SERVER_ADDRESS
              value: "10.0.0.11"
          ports:
            - containerPort: 389

          resources:
            limits:
              memory: "100Mi"
              cpu: "50m"
            requests:
              memory: "30Mi"
              cpu: "10m"