apiVersion: apps/v1
kind: Deployment
metadata:
  name: flais-nam-oauth-client-validator
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/path: /infra/nam/oauth/clients/validator/actuator/prometheus
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      hostAliases:
        - ip: "10.0.0.11"
          hostnames:
            - "namadmcon01"
      volumes:
        - name: secrets
          secret:
            secretName: "namadmcon01"
            items:
              - key: cacerts.jks
                path: cacerts.jks
      containers:
        - name: flais-nam-oauth-client-validator
          securityContext:
            {}
          image: "ghcr.io/fintlabs/flais-nam-oauth-client-validator:sha-0000000"
          imagePullPolicy: IfNotPresent
          env:
            - name: logging.level.no.fintlabs
              value: DEBUG
            - name: spring.webflux.base-path
              value: /infra/nam/oauth/clients/validator
          envFrom:
            - secretRef:
                name: flais-nam-oauth-client-validator
          volumeMounts:
            - name: secrets
              mountPath: /mnt/secrets
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /infra/nam/oauth/clients/validator/actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /infra/nam/oauth/clients/validator/actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 5
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
            requests:
              memory: 256Mi
              cpu: 250m